name: Profile 3D GitHub

on:
  schedule:
    - cron: "0 */18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Profile 3D GitHub
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name ahmaddyd
          git config user.email ahmdyulian.86@gmail.com
          git add -A .
          git commit -m "Û¶ðŸ‘¾Profile 3D GitHub UpdatedðŸ”¥Ù©"
          git push
